### ISSUE TITLE
Many jobs launched for 1 Distiller operation

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/distiller#673] opened 2023-01-10 21:07 UTC
Distiller operations are doing something strange.

Perlmutter transfers show an error, but Cori operations show success. Check out job 3937 for example.

I believe the issue is that several jobs (7 in one instance) are launched at the same on Cori and Perlmutter time doing the same work. So, I think that there is something incorrect with the job submission process. 

Also, Distiller no longer shows a slurm ID.

Cori:
1. Press **transfer** on Distiller and select Cori
2. `sqs -u dstlr` on Cori
3. Many jobs are launched concurrently.
```
percius@cori10:~> sqs -u dstlr
JOBID            ST USER      NAME          NODES TIME_LIMIT       TIME  SUBMIT_TIME          QOS             START_TIME           FEATURES       NODELIST(REASON
65817474         CG dstlr     distiller-tr  1          30:00       0:13  2023-01-10T12:55:59  realtime_m3795  2023-01-10T12:56:02  haswell        nid00573
65817482         PD dstlr     distiller-tr  20         30:00       0:00  2023-01-10T12:56:15  realtime_m3795  N/A                  haswell        (QOSGrpNodeLimi
65817480         PD dstlr     distiller-tr  20         30:00       0:00  2023-01-10T12:56:08  realtime_m3795  N/A                  haswell        (QOSGrpNodeLimi
65817477         PD dstlr     distiller-tr  20         30:00       0:00  2023-01-10T12:56:02  realtime_m3795  N/A                  haswell        (QOSGrpNodeLimi
65817476         R  dstlr     distiller-tr  20         30:00       0:08  2023-01-10T12:55:59  realtime_m3795  2023-01-10T12:56:15  haswell        nid00[713-732]
```

Perlmutter shows a similar behavior.

Counting jobs do the same thing:
1. Press **count** on Distiller
2. `sqs -u dstlr` on Cori:
3. Many jobs are launched concurrently
```
percius@cori10:~> sqs -u dstlr
JOBID            ST USER      NAME          NODES TIME_LIMIT       TIME  SUBMIT_TIME          QOS             START_TIME           FEATURES       NODELIST(REASON
65817567         PD dstlr     distiller-co  20         30:00       0:00  2023-01-10T13:02:04  realtime_m3795  2023-01-10T13:02:20  haswell        (QOSGrpNodeLimi
65817568         PD dstlr     distiller-co  20         30:00       0:00  2023-01-10T13:02:04  realtime_m3795  2023-01-10T13:02:20  haswell        (QOSGrpNodeLimi
65817570         PD dstlr     distiller-co  20         30:00       0:00  2023-01-10T13:02:11  realtime_m3795  2023-01-10T13:02:20  haswell        (BurstBufferSta
65817572         PD dstlr     distiller-co  20         30:00       0:00  2023-01-10T13:02:14  realtime_m3795  N/A                  haswell        (BurstBufferRes
65817565         R  dstlr     distiller-co  20         30:00       0:20  2023-01-10T13:01:51  realtime_m3795  2023-01-10T13:02:00  haswell        nid0[0748-0757,
```

A little while later Distiller showed "completed" but `sqs -u dstlr` showed many more jobs still in the queue
```
percius@cori10:~> sqs -u dstlr
JOBID            ST USER      NAME          NODES TIME_LIMIT       TIME  SUBMIT_TIME          QOS             START_TIME           FEATURES       NODELIST(REASON
65817601         PD dstlr     distiller-co  20         30:00       0:00  2023-01-10T13:03:04  realtime_m3795  N/A                  haswell        (QOSGrpNodeLimi
65817597         PD dstlr     distiller-co  20         30:00       0:00  2023-01-10T13:02:49  realtime_m3795  N/A                  haswell        (QOSGrpNodeLimi
65817593         PD dstlr     distiller-co  20         30:00       0:00  2023-01-10T13:02:40  realtime_m3795  N/A                  haswell        (QOSGrpNodeLimi
65817590         PD dstlr     distiller-co  20         30:00       0:00  2023-01-10T13:02:30  realtime_m3795  N/A                  haswell        (QOSGrpNodeLimi
65817587         R  dstlr     distiller-co  20         30:00       0:18  2023-01-10T13:02:20  realtime_m3795  2023-01-10T13:04:27  haswell        nid00[713-732]
```

**Comment by cjh1** [comment] 2023-01-11 20:34
@ercius Got to the bottom of this. It was caused by a bug in the SF API introduced by a recent change, should be fixed up now.

**Closed by cjh1** 2023-01-11 20:34 UTC
